# frozen_string_literal: true

tasks_attributes = [
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Heavy Equipment Operation", "description": "Operating machines like bulldozers and excavators."},
  {"organization_id": "Red", "category": "Concrete", "name": "Swimming Pool Installation", "description": "Constructing swimming pools with concrete and tiles."},
  {"organization_id": "Blue", "category": "Flooring", "name": "Hardwood Flooring Installation", "description": "Installing hardwood boards for durable flooring."},
  {"organization_id": "Red", "category": "Masonry", "name": "Laying Concrete Blocks", "description": "Building walls using concrete blocks and mortar."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building Custom Shelving", "description": "Constructing custom-built shelving for storage solutions."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Utility Trenching", "description": "Digging trenches to lay down utility lines like water, gas, or electricity."},
  {"organization_id": "Red", "category": "Exterior", "name": "Installing Pool Fences", "description": "Setting up fences around swimming pools for safety."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Installing Gravel Driveways", "description": "Laying gravel to create durable, permeable driveways."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Staircase Installation", "description": "Building and installing staircases inside or outside the structure."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Bathtub Installation", "description": "Installing bathtubs in bathrooms."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Road Surface Grading", "description": "Grading roads to prepare for paving or repairs."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Repairing Leaking Faucets", "description": "Fixing or replacing worn-out parts in faucets to stop leaks."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building a Firewood Shed", "description": "Constructing small sheds to store firewood."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Installing Patio Covers", "description": "Building or installing covers to protect patios from the weather."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Window Fitting", "description": "Placing and sealing windows in prepared openings."},
  {"organization_id": "Red", "category": "Drywall", "name": "Drywall Installation", "description": "Hanging drywall sheets to form the interior walls and ceilings."},
  {"organization_id": "Blue", "category": "Structural", "name": "Rebar Installation", "description": "Placing rebar in forms for reinforced concrete structures."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Greenhouse Construction", "description": "Building a greenhouse for plants and agriculture."},
  {"organization_id": "Red", "category": "Exterior", "name": "Fence Repair Work", "description": "Fixing or replacing damaged fence sections."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Termite Treatment", "description": "Applying treatments to prevent termite damage to wood structures."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Kitchen Cabinet Fitting", "description": "Installing cabinetry in the kitchen."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building Pergola Covers", "description": "Adding covers to pergolas for increased shade and protection."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Trailer Installation", "description": "Placing trailers for storage or office space on construction sites."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Water Softener Installation", "description": "Setting up a system to reduce mineral content in water."},
  {"organization_id": "Red", "category": "Insulation", "name": "Adding Insulation to Existing Structures", "description": "Installing additional insulation to improve energy efficiency in older buildings."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Installing Tankless Water Heaters", "description": "Setting up energy-efficient tankless water heaters."},
  {"organization_id": "Red", "category": "Masonry", "name": "Chimney Installation", "description": "Building or installing chimneys for fireplaces."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Tree Removal", "description": "Cutting down and removing trees from the construction site."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building a Deck", "description": "Constructing a deck for outdoor spaces."},
  {"organization_id": "Red", "category": "Exterior", "name": "Fence Gate Setup", "description": "Installing gates in fences for easy access."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Hanging Doors", "description": "Installing interior and exterior doors."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Retaining Wall Construction", "description": "Building retaining walls to hold back soil on sloped landscapes."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Excavation", "description": "Digging and removing soil to prepare the site for construction."},
  {"organization_id": "Blue", "category": "Interior", "name": "Ceiling Tile Installation", "description": "Placing tiles on the ceiling for aesthetic and acoustic purposes."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Landscaping Grading", "description": "Leveling and shaping the ground for landscaping or drainage."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Soil Compaction", "description": "Compacting soil to provide a stable base for construction."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Fitting Industrial Doors", "description": "Installing large industrial doors in factories or warehouses."},
  {"organization_id": "Red", "category": "Flooring", "name": "Wood Floor Installation", "description": "Installing wooden planks or panels for flooring."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Road Grading", "description": "Leveling roads to prepare for paving or construction."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building Wooden Planters", "description": "Constructing wooden planter boxes for gardens."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Assembling Prefabricated Buildings", "description": "Constructing buildings from pre-made components."},
  {"organization_id": "Red", "category": "Masonry", "name": "Driveway Paving", "description": "Creating a smooth surface for driveways using asphalt or concrete."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Building Retaining Walls", "description": "Constructing walls to prevent soil erosion."},
  {"organization_id": "Red", "category": "Masonry", "name": "Building Retaining Walls", "description": "Constructing walls to hold back soil and manage landscape elevation."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Drilling", "description": "Drilling holes in concrete for pipes or bolts."},
  {"organization_id": "Red", "category": "Roofing", "name": "Laying Asphalt Shingles", "description": "Installing asphalt shingles on roofs for waterproofing and protection."},
  {"organization_id": "Red", "category": "Exterior", "name": "Replacing Damaged Siding", "description": "Removing and replacing broken or weathered siding on buildings."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Gas Line Installation", "description": "Installing and testing gas lines for heating or cooking appliances."},
  {"organization_id": "Red", "category": "Roofing", "name": "Ventilation System Setup", "description": "Installing roof vents to promote air circulation."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Shower Enclosure Installation", "description": "Setting up glass or acrylic enclosures for showers."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Intercom Systems", "description": "Installing intercoms for communication between rooms or floors."},
  {"organization_id": "Blue", "category": "Structural", "name": "Curtain Wall Installation", "description": "Installing non-load-bearing exterior walls made of glass or metal."},
  {"organization_id": "Red", "category": "Waterproofing", "name": "Basement Sealing", "description": "Waterproofing the basement to prevent leaks and moisture issues."},
  {"organization_id": "Red", "category": "Electrical", "name": "Setting Up Floodlights", "description": "Installing floodlights for security or outdoor illumination."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Door Installation", "description": "Installing interior and exterior doors."},
  {"organization_id": "Blue", "category": "Painting", "name": "Exterior Painting", "description": "Applying paint to the exterior walls of the building."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Constructing Dog Houses", "description": "Building small wooden shelters for pets."},
  {"organization_id": "Red", "category": "Masonry", "name": "Restoring Old Masonry", "description": "Repairing and restoring deteriorated brick or stonework."},
  {"organization_id": "Red", "category": "Insulation", "name": "Installing Air Barriers", "description": "Adding air barriers to walls for improved energy efficiency."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Fire Alarm System Installation", "description": "Installing and connecting fire alarm systems for safety."},
  {"organization_id": "Red", "category": "Roofing", "name": "Gutter System Installation", "description": "Attaching gutters to the roof to manage rainwater."},
  {"organization_id": "Red", "category": "Interior", "name": "Installing Wood Paneling", "description": "Adding wood paneling to interior walls for a rustic look."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Setting Up Exterior Spotlights", "description": "Installing spotlights to illuminate building exteriors."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Stamping", "description": "Adding decorative patterns to freshly poured concrete."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Security Systems", "description": "Setting up cameras, sensors, and alarms for security."},
  {"organization_id": "Red", "category": "Concrete", "name": "Concrete Crack Repair", "description": "Fixing cracks in concrete surfaces."},
  {"organization_id": "Red", "category": "Masonry", "name": "Sealing Concrete Surfaces", "description": "Applying sealant to concrete to protect against moisture and stains."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Installing Stairway Railings", "description": "Placing handrails along stairways for safety."},
  {"organization_id": "Red", "category": "Masonry", "name": "Building Concrete Patios", "description": "Constructing concrete surfaces for outdoor living spaces."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Fence Repair", "description": "Fixing broken or damaged fences around the property."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Toilet Installation", "description": "Mounting and connecting toilets to the plumbing system."},
  {"organization_id": "Red", "category": "Concrete", "name": "Concrete Foundation Pouring", "description": "Pouring concrete for the foundation or footings."},
  {"organization_id": "Blue", "category": "Structural", "name": "Welding Metal Components", "description": "Welding metal parts together for structural integrity."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Balcony Construction", "description": "Building balconies attached to the building's exterior."},
  {"organization_id": "Red", "category": "Concrete", "name": "Fixing Foundation Issues", "description": "Repairing cracks or settling in foundations."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Stucco Application", "description": "Applying stucco to exterior walls for a durable finish."},
  {"organization_id": "Red", "category": "Fire Safety", "name": "Installing Safety Nets", "description": "Setting up safety nets around construction sites to protect workers."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Grading and Leveling", "description": "Leveling the ground to prepare for landscaping or construction."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Soundproofing Installation", "description": "Adding materials to walls and ceilings to reduce noise transmission."},
  {"organization_id": "Blue", "category": "Flooring", "name": "Tile Flooring Installation", "description": "Laying down tiles for flooring in kitchens, bathrooms, and hallways."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Scaffolding Dismantling", "description": "Taking down scaffolding after construction is complete."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Electrical Grounding", "description": "Ensuring proper grounding of the building's electrical system."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing a Pergola", "description": "Building a pergola for outdoor shading or decor."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Driveway Resurfacing", "description": "Restoring damaged driveways with new materials."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Erecting Gazebos", "description": "Building outdoor gazebos for shelter and relaxation."},
  {"organization_id": "Red", "category": "Electrical", "name": "Low Voltage Wiring", "description": "Installing wiring for low voltage systems like alarms and speakers."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Assembling Metal Sheds", "description": "Building prefabricated metal sheds for storage."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Finishing", "description": "Smoothing and finishing concrete surfaces after pouring."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Storm Shutter Installation", "description": "Placing shutters to protect windows from storms."},
  {"organization_id": "Red", "category": "Interior", "name": "Fitting Shower Curtains", "description": "Installing rods and curtains for shower enclosures."},
  {"organization_id": "Red", "category": "Masonry", "name": "Stone Cladding Installation", "description": "Attaching decorative stone veneers to walls."},
  {"organization_id": "Red", "category": "Concrete", "name": "Concrete Curing", "description": "Ensuring proper curing of concrete for long-term strength and durability."},
  {"organization_id": "Blue", "category": "Flooring", "name": "Applying Epoxy Floor Coatings", "description": "Applying epoxy coatings for durability and easy maintenance on floors."},
  {"organization_id": "Red", "category": "Masonry", "name": "Paving Parking Lots", "description": "Laying asphalt or concrete for parking areas."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Assembling Gazebos", "description": "Constructing outdoor gazebos for relaxation or gatherings."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Repairing Roof Flashing", "description": "Fixing flashing around chimneys or vents to prevent leaks."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Slab Pouring", "description": "Pouring concrete to create flat surfaces like patios and driveways."},
  {"organization_id": "Red", "category": "Insulation", "name": "Insulation Setup", "description": "Installing insulation to regulate temperature and reduce noise."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Septic System Installation", "description": "Setting up a septic system for waste management in areas without sewer access."},
  {"organization_id": "Red", "category": "Drywall", "name": "Applying Skim Coat", "description": "Applying a thin layer of plaster to smooth out wall surfaces."},
  {"organization_id": "Red", "category": "Exterior", "name": "Installing Fence Posts", "description": "Setting up posts to support fencing around properties."},
  {"organization_id": "Red", "category": "Electrical", "name": "Temporary Power Setup", "description": "Providing temporary power for tools and machinery on the job site."},
  {"organization_id": "Red", "category": "Roofing", "name": "Shingle Removal", "description": "Removing old shingles in preparation for new roof installation."},
  {"organization_id": "Blue", "category": "Structural", "name": "Underpinning Foundations", "description": "Strengthening existing foundations by adding supports."},
  {"organization_id": "Blue", "category": "HVAC", "name": "Underfloor Heating Installation", "description": "Placing systems to heat floors for comfort."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Temporary Power Installation", "description": "Setting up generators or temporary power sources for construction sites."},
  {"organization_id": "Blue", "category": "Structural", "name": "Steel Beam Installation", "description": "Placing steel beams for structural support in large buildings."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing Door Locks", "description": "Fitting and securing locks on doors for added security."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Demolition", "description": "Tearing down existing structures to clear space for new construction."},
  {"organization_id": "Red", "category": "Roofing", "name": "Installing Downspouts", "description": "Connecting downspouts to gutters to direct water away from the building foundation."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Hot Tub Installation", "description": "Installing hot tubs and connecting them to water and electricity."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Hardscaping", "description": "Building paths, patios, and other hard surface areas in landscaping projects."},
  {"organization_id": "Blue", "category": "Waterproofing", "name": "Foundation Waterproofing", "description": "Sealing the foundation to prevent water damage."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Safety Net Installation", "description": "Placing safety nets around construction sites to protect workers."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Planting Trees and Shrubs", "description": "Adding trees, shrubs, and plants around the property."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Deck Construction", "description": "Building a deck attached to the exterior of the building."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Repairing Plumbing Leaks", "description": "Identifying and fixing leaks in water supply pipes."},
  {"organization_id": "Red", "category": "Concrete", "name": "Finishing Concrete", "description": "Smoothing and finishing freshly poured concrete surfaces."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Electrical Outlet Installation", "description": "Placing electrical outlets in walls."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Attic Ladder Installation", "description": "Placing pull-down ladders for access to the attic."},
  {"organization_id": "Red", "category": "HVAC", "name": "Installing Greenhouse Fans", "description": "Setting up ventilation systems to regulate greenhouse temperatures."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Formwork Construction", "description": "Building forms to hold concrete in place while it cures."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Electrical Rough-In", "description": "Setting up electrical wiring and outlets throughout the building."},
  {"organization_id": "Red", "category": "Roofing", "name": "Skylight Installation", "description": "Fitting skylights to bring natural light into the building."},
  {"organization_id": "Red", "category": "Masonry", "name": "Constructing Barbecue Pits", "description": "Building permanent barbecue structures in backyards."},
  {"organization_id": "Red", "category": "Waterproofing", "name": "Waterproofing a Foundation", "description": "Applying sealants to prevent foundation leaks."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Roof Vent Installation", "description": "Adding vents to the roof for airflow and temperature regulation."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Plumbing Rough-In", "description": "Installing basic plumbing infrastructure for water and drainage."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Constructing Timber Retaining Walls", "description": "Building wooden retaining walls for landscaping projects."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Erecting Metal Fencing", "description": "Building fences using metal posts and wire mesh."},
  {"organization_id": "Blue", "category": "HVAC", "name": "HVAC Ductwork Installation", "description": "Installing ductwork for heating and cooling systems."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Attic Vent Installation", "description": "Installing vents in the attic to allow for airflow."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Retrofitting Insulation", "description": "Adding insulation to existing structures for better energy efficiency."},
  {"organization_id": "Red", "category": "Concrete", "name": "Tilt-Up Concrete Construction", "description": "Building large panels of concrete and tilting them into position."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Laying Gravel Paths", "description": "Spreading gravel to create paths or driveways."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Bricklaying", "description": "Building walls or pathways using bricks and mortar."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Hydroseeding", "description": "Spraying a mixture of seeds and mulch to encourage rapid grass growth."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Shower Unit Installation", "description": "Installing pre-built shower units or custom shower systems."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Soffit Installation", "description": "Placing soffit panels beneath roof overhangs for ventilation."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Fence Staining", "description": "Applying stain to wooden fences for protection and aesthetic purposes."},
  {"organization_id": "Red", "category": "Exterior", "name": "Storm Door Installation", "description": "Installing storm doors to protect main doors from harsh weather."},
  {"organization_id": "Red", "category": "Exterior", "name": "Fence Construction", "description": "Building fences around the property for privacy or security."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Solar Water Heater Installation", "description": "Installing solar-powered systems to heat water."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Barbed Wire Installation", "description": "Setting up barbed wire for added security on fences."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Constructing Concrete Steps", "description": "Building durable concrete steps for entrances or patios."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Ceiling Fan Installation", "description": "Installing ceiling fans for air circulation."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Interior Demolition", "description": "Tearing down interior walls or features for remodeling."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Building Wooden Fences", "description": "Constructing wooden fences around property lines."},
  {"organization_id": "Red", "category": "Electrical", "name": "Upgrading Electrical Panel", "description": "Replacing or upgrading the main electrical panel for added capacity."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Constructing Barn Doors", "description": "Building sliding barn doors for rustic or industrial design."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Excavation Compaction", "description": "Compacting soil to ensure stability before construction."},
  {"organization_id": "Red", "category": "Flooring", "name": "Ceramic Tile Installation", "description": "Laying ceramic tiles in bathrooms, kitchens, or other areas."},
  {"organization_id": "Blue", "category": "Drywall", "name": "Cement Board Installation", "description": "Placing cement boards for moisture resistance in bathrooms."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Fixing Cracked Walls", "description": "Repairing cracks in walls using patching material or mortar."},
  {"organization_id": "Red", "category": "Roofing", "name": "Vent Installation", "description": "Adding roof or wall vents to regulate temperature and moisture."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Power Generators", "description": "Setting up backup power generators for homes or businesses."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Door Frame Installation", "description": "Building and installing door frames for interior and exterior doors."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Gutter Installation", "description": "Placing gutters on the roof to direct rainwater away from the building."},
  {"organization_id": "Red", "category": "Masonry", "name": "Asphalt Repair", "description": "Repairing damaged asphalt driveways or roads."},
  {"organization_id": "Red", "category": "Electrical", "name": "Electrical Grounding Installation", "description": "Ensuring the electrical system is properly grounded."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Deck Lighting", "description": "Setting up lighting fixtures on decks for nighttime use."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Siding Installation", "description": "Applying siding materials like vinyl or wood to the exterior of a building."},
  {"organization_id": "Red", "category": "Concrete", "name": "Building Formwork", "description": "Creating formwork molds for concrete pouring."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fireproof Door Installation", "description": "Placing fire-resistant doors to prevent the spread of flames."},
  {"organization_id": "Red", "category": "Exterior", "name": "Termite Protection Setup", "description": "Applying treatments to prevent termite damage to wood structures."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing Energy-Efficient Windows", "description": "Replacing windows with energy-saving alternatives to reduce heating and cooling costs."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Excavating for Swimming Pools", "description": "Digging out space for a swimming pool installation."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Drainage System Installation", "description": "Setting up systems to redirect water away from the building."},
  {"organization_id": "Red", "category": "Structural", "name": "Tying Rebar", "description": "Tying reinforcing bars together for concrete structures."},
  {"organization_id": "Blue", "category": "Structural", "name": "Foundation Piering", "description": "Adding piers under the foundation to prevent settling."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Pergola Installation", "description": "Building a pergola structure for outdoor shade and decoration."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Installing Artificial Turf", "description": "Laying artificial grass for low-maintenance lawns."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Foundation Repair", "description": "Fixing cracks or damage to the building's foundation."},
  {"organization_id": "Red", "category": "Exterior", "name": "Curtain Wall Installation", "description": "Installing non-load-bearing curtain walls made of glass or aluminum."},
  {"organization_id": "Red", "category": "Flooring", "name": "Epoxy Coating for Garage Floors", "description": "Applying epoxy to garage floors for protection and appearance."},
  {"organization_id": "Red", "category": "Masonry", "name": "Resurfacing Driveways", "description": "Restoring and resurfacing driveways with asphalt or concrete."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Installing Underground Water Pipes", "description": "Laying water supply pipes underground for buildings."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing Attic Ladders", "description": "Fitting pull-down ladders for easy access to attic spaces."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Excavation Backfilling", "description": "Filling trenches or holes after underground utilities are placed."},
  {"organization_id": "Red", "category": "Roofing", "name": "Installing Temporary Roofing", "description": "Setting up temporary roofing to protect workers and materials."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Resurfacing", "description": "Applying a new layer of concrete to restore damaged surfaces."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fall Protection System Installation", "description": "Setting up fall protection systems for worker safety."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Backfilling Excavations", "description": "Filling trenches or holes with soil after utilities have been installed."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Backflow Preventer Installation", "description": "Installing devices to prevent contamination of the water supply."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Sealing Roof Leaks", "description": "Identifying and sealing leaks in roof systems."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Window Flashing Installation", "description": "Installing flashing around windows to prevent water leaks."},
  {"organization_id": "Red", "category": "Fire Safety", "name": "Installing Fall Protection Systems", "description": "Setting up fall protection equipment for worker safety on high structures."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Low Voltage Wiring Installation", "description": "Installing wiring for low voltage systems like alarms and speakers."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Chimney Repair", "description": "Fixing cracks and damage to chimneys."},
  {"organization_id": "Red", "category": "Masonry", "name": "Chimney Maintenance", "description": "Cleaning and repairing chimneys."},
  {"organization_id": "Red", "category": "Masonry", "name": "Constructing Fireplaces", "description": "Building brick or stone fireplaces inside homes."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Temporary Roof Installation", "description": "Setting up temporary roofing to protect ongoing work from weather."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Site Clearing", "description": "Removing trees, debris, and other obstructions to prepare the site for construction."},
  {"organization_id": "Blue", "category": "Structural", "name": "Structural Steel Erection", "description": "Building the steel framework for large structures."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Safety Rail Installation", "description": "Installing railings to prevent falls on staircases or balconies."},
  {"organization_id": "Red", "category": "Electrical", "name": "Setting Up Emergency Exit Signs", "description": "Installing illuminated exit signs for safety in buildings."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing Door Frames", "description": "Building and installing frames for doors."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Installing Electrical Panels", "description": "Setting up electrical panels to distribute power throughout the building."},
  {"organization_id": "Red", "category": "Exterior", "name": "Installing Glass Railings", "description": "Fitting glass panels for deck or balcony railings."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Hydroseeding", "description": "Applying a mixture of seed, water, and mulch to promote grass growth."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Paving Walkways", "description": "Laying stones or bricks to create paths through gardens or yards."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Hot Tub Setup", "description": "Installing and connecting hot tubs to plumbing and electrical systems."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Wheelchair Ramp Construction", "description": "Building ramps for accessibility."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing Solar Water Heaters", "description": "Setting up solar-powered systems for heating water."},
  {"organization_id": "Blue", "category": "Interior", "name": "Installing Suspended Ceilings", "description": "Fitting suspended ceiling panels in offices or commercial buildings."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Installing French Drains", "description": "Setting up drainage systems to manage water flow in landscapes."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fireproofing", "description": "Applying materials that prevent the spread of fire in buildings."},
  {"organization_id": "Red", "category": "Masonry", "name": "Brickwork", "description": "Building walls or structures using bricks and mortar."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Storm Door Installation", "description": "Placing storm doors to protect the main doors from weather."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Laying Cobblestones", "description": "Arranging cobblestones for walkways or driveways."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Paving Driveway", "description": "Creating a smooth surface for driveways with concrete or asphalt."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Installing Job Site Trailers", "description": "Setting up trailers for offices or storage on construction sites."},
  {"organization_id": "Red", "category": "Roofing", "name": "Installing Metal Roofing", "description": "Attaching metal roofing sheets for durability."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Drainage System Installation", "description": "Setting up drainage systems to manage rainwater runoff."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Installing Motion Sensors", "description": "Setting up motion sensors for security or lighting."},
  {"organization_id": "Red", "category": "Interior", "name": "Installing Floating Shelves", "description": "Placing floating shelves for storage and decoration in rooms."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Installing Window Flashing", "description": "Sealing windows with flashing to prevent water ingress."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Window Installation", "description": "Placing windows in frames and sealing them for insulation."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fire Escape Installation", "description": "Building external fire escape staircases."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Deck Rail Installation", "description": "Installing rails around decks for safety and aesthetics."},
  {"organization_id": "Red", "category": "Exterior", "name": "Gate Installation", "description": "Installing gates for driveways or pedestrian access."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Curing", "description": "Ensuring proper curing of concrete to increase its strength and durability."},
  {"organization_id": "Red", "category": "Fire Safety", "name": "Fireproofing Structures", "description": "Adding fire-resistant materials to structural elements."},
  {"organization_id": "Red", "category": "Structural", "name": "Seismic Retrofitting", "description": "Strengthening buildings to withstand earthquakes."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Demolition Work", "description": "Removing old structures to make room for new construction."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Gas Line Installation", "description": "Setting up gas lines for heating or cooking appliances."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Cabinet Installation", "description": "Installing cabinets in kitchens or bathrooms."},
  {"organization_id": "Red", "category": "Masonry", "name": "Asphalt Driveway Installation", "description": "Laying asphalt to create a smooth, durable driveway surface."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Surveying the Construction Site", "description": "Conducting a survey to measure and map the site."},
  {"organization_id": "Red", "category": "Interior", "name": "Installing Acoustic Ceiling Tiles", "description": "Placing tiles to improve soundproofing in rooms or offices."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Wall Framing", "description": "Constructing the wooden or metal framework for walls."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Installing Landscape Lighting", "description": "Setting up outdoor lighting for gardens and paths."},
  {"organization_id": "Red", "category": "Masonry", "name": "Installing Outdoor Fireplaces", "description": "Building fireplaces for outdoor living areas."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Constructing Bicycle Sheds", "description": "Building small shelters for storing bicycles."},
  {"organization_id": "Red", "category": "Roofing", "name": "Replacing Fascia Boards", "description": "Swapping out damaged fascia boards along the roofline."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Installing Wooden Beams", "description": "Placing decorative or structural wooden beams."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Installing Rainwater Collection Systems", "description": "Setting up systems to collect and store rainwater."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Fireplace Installation", "description": "Building or installing a fireplace inside the structure."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Pipe Insulation Installation", "description": "Adding insulation to pipes to prevent freezing or heat loss."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Trenching for Utilities", "description": "Digging trenches to lay utility lines for water, gas, or power."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Porch Construction", "description": "Building a porch at the entrance of the building."},
  {"organization_id": "Red", "category": "HVAC", "name": "HVAC Installation", "description": "Installing heating, ventilation, and air conditioning systems."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Handrail Installation", "description": "Placing handrails for safety on stairs or walkways."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Asphalt Sealing", "description": "Applying a protective coating to asphalt surfaces to extend their lifespan."},
  {"organization_id": "Red", "category": "Electrical", "name": "Wind Turbine Installation", "description": "Installing wind turbines for renewable energy generation."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Tree Planting", "description": "Planting trees around the property for shade or decoration."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Temporary Structure Erection", "description": "Building temporary structures like scaffolding or tents."},
  {"organization_id": "Red", "category": "Insulation", "name": "Installing Vapor Barriers", "description": "Placing vapor barriers to prevent moisture buildup inside walls."},
  {"organization_id": "Blue", "category": "HVAC", "name": "Air Conditioning Unit Installation", "description": "Placing and connecting air conditioning units."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Constructing Treehouses", "description": "Building treehouses for recreational or decorative purposes."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Repairing Stairs", "description": "Fixing broken or damaged steps in staircases."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Garage Insulation Installation", "description": "Adding insulation to the garage for energy efficiency."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Metal Stud Framing", "description": "Building frameworks for walls using metal studs."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Staircase Installation", "description": "Constructing and installing stairways inside or outside the home."},
  {"organization_id": "Blue", "category": "Tiling", "name": "Tiling Shower Walls", "description": "Installing tiles in showers for waterproofing and aesthetics."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Septic Tank Repair", "description": "Fixing leaks or damage to septic tanks."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing Hot Water Circulation Systems", "description": "Setting up systems to keep hot water readily available."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Light Fixture Installation", "description": "Placing and connecting light fixtures in rooms."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Gas Pipe Leak Detection", "description": "Checking gas lines for leaks and repairing them."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building Storage Closets", "description": "Constructing built-in closets for additional storage in rooms."},
  {"organization_id": "Red", "category": "Exterior", "name": "Building Temporary Fencing", "description": "Installing temporary fences to secure the construction site."},
  {"organization_id": "Red", "category": "Exterior", "name": "Staining a Fence", "description": "Applying stain to protect and color wooden fences."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Reinforcing Rebar Installation", "description": "Placing rebar to reinforce concrete structures."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Greenhouse Construction", "description": "Building a greenhouse for growing plants."},
  {"organization_id": "Red", "category": "Concrete", "name": "Decorative Concrete Stamping", "description": "Adding stamped patterns to concrete for aesthetic purposes."},
  {"organization_id": "Red", "category": "Waterproofing", "name": "Installing Waterproof Membranes", "description": "Applying membranes to prevent water penetration in walls or roofs."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Building Retaining Walls", "description": "Constructing walls to hold back soil and manage slopes."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Demolishing Interiors", "description": "Removing interior walls or structures in renovation projects."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Manhole Cover Installation", "description": "Installing covers to allow access to underground utilities."},
  {"organization_id": "Blue", "category": "Drywall", "name": "Drywall Hanging", "description": "Mounting drywall panels to frame walls and ceilings."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Installing a Sprinkler Timer", "description": "Setting up timers for automatic lawn irrigation systems."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Installing Driveway Gates", "description": "Setting up automatic or manual gates at the entrance of driveways."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Grading", "description": "Leveling the ground for proper drainage and construction."},
  {"organization_id": "Red", "category": "Exterior", "name": "Constructing Wheelchair Ramps", "description": "Building ramps to ensure accessibility for wheelchair users."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Solar Panel Installation", "description": "Mounting solar panels on the roof to generate energy."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Roof Installation", "description": "Installing roof materials such as shingles or metal panels."},
  {"organization_id": "Red", "category": "Exterior", "name": "Siding Installation", "description": "Attaching siding materials like vinyl, aluminum, or wood to the exterior."},
  {"organization_id": "Red", "category": "Concrete", "name": "Foundation Construction", "description": "Building the foundation that supports the entire structure."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Air Barrier Installation", "description": "Applying air barriers to walls for improved energy efficiency."},
  {"organization_id": "Red", "category": "Flooring", "name": "Laying Vinyl Flooring", "description": "Installing vinyl flooring for durability and water resistance."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building a Porch", "description": "Constructing a porch at the entrance of a building."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Pipe Insulation Setup", "description": "Insulating pipes to prevent freezing or heat loss."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Temporary Fencing Installation", "description": "Building fences around construction sites for security."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Crown Molding Installation", "description": "Placing decorative molding at the top of walls."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Foundation Excavation", "description": "Digging out space for the foundation of a building."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Storm Drain Installation", "description": "Setting up drainage systems to manage rainwater on roads."},
  {"organization_id": "Red", "category": "Tiling", "name": "Tiling Kitchen Backsplashes", "description": "Installing decorative tiles behind kitchen counters to protect walls."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Skylight Installation", "description": "Placing skylights in the roof to bring in natural light."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Pest Control Installation", "description": "Setting up barriers and treatments to prevent pests from entering the building."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Molding Installation", "description": "Installing decorative trim or crown molding in rooms."},
  {"organization_id": "Blue", "category": "Drywall", "name": "Skim Coating", "description": "Applying a thin layer of plaster for smooth wall finishes."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Stone Veneer Installation", "description": "Applying stone veneer to surfaces for decorative purposes."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Installing Spray Foam Insulation", "description": "Using spray foam to insulate walls and ceilings."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Carport Construction", "description": "Building a shelter for cars attached to a home or building."},
  {"organization_id": "Red", "category": "Interior", "name": "Installing Shower Grab Bars", "description": "Fitting grab bars in showers for safety and support."},
  {"organization_id": "Red", "category": "Concrete", "name": "Concrete Resurfacing", "description": "Applying new layers of concrete to restore old surfaces."},
  {"organization_id": "Red", "category": "Interior", "name": "Replacing Ceiling Tiles", "description": "Swapping out old or damaged ceiling tiles in commercial or residential buildings."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Landscaping", "description": "Designing and planting greenery around the property."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Electrical Panel Upgrade", "description": "Replacing or upgrading the electrical panel for better capacity."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Vapor Barrier Installation", "description": "Installing vapor barriers to prevent moisture from penetrating walls."},
  {"organization_id": "Red", "category": "Insulation", "name": "Sealing Drafty Windows", "description": "Sealing windows to improve insulation and prevent drafts."},
  {"organization_id": "Blue", "category": "Insulation", "name": "Insulation Installation", "description": "Adding insulation material to walls and attics."},
  {"organization_id": "Blue", "category": "Flooring", "name": "Garage Floor Epoxy Coating", "description": "Applying epoxy coatings to protect and enhance garage floors."},
  {"organization_id": "Blue", "category": "Painting", "name": "Repainting House Exteriors", "description": "Repainting the exterior walls of homes for maintenance and aesthetics."},
  {"organization_id": "Red", "category": "Masonry", "name": "Repairing Water Damage", "description": "Fixing damaged walls, ceilings, or floors affected by water."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Erosion Control", "description": "Setting up barriers and plants to prevent soil erosion around the building."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Deck Staining", "description": "Staining a wooden deck to protect it from weather and wear."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fire Exit Installation", "description": "Building exits designed for emergency evacuations."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Installing Sliding Doors", "description": "Fitting sliding doors for closets or patios."},
  {"organization_id": "Red", "category": "Insulation", "name": "Garage Insulation", "description": "Adding insulation to garage walls for temperature control."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Erosion Prevention Measures", "description": "Installing barriers or plants to reduce soil erosion."},
  {"organization_id": "Red", "category": "Roofing", "name": "Replacing Gutters", "description": "Swapping out old gutters with new ones to improve drainage."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Awning Installation", "description": "Installing awnings over windows or doors for shade."},
  {"organization_id": "Red", "category": "Exterior", "name": "Pest Prevention Barriers", "description": "Installing barriers to keep pests from entering buildings."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Power Outlets", "description": "Placing electrical outlets and wiring them for power."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Constructing Pergolas", "description": "Building pergolas for outdoor shade and decoration."},
  {"organization_id": "Red", "category": "Masonry", "name": "Repairing Chimney Caps", "description": "Fixing or replacing caps on chimneys to prevent water damage."},
  {"organization_id": "Blue", "category": "Flooring", "name": "Vinyl Flooring Installation", "description": "Placing vinyl sheets or planks for easy-to-maintain flooring."},
  {"organization_id": "Red", "category": "Roofing", "name": "Green Roof Installation", "description": "Building a green roof with vegetation for insulation and sustainability."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Deck Staining", "description": "Staining wood decks to protect from weather and wear."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Plumbing Installation", "description": "Installing pipes for water supply and drainage systems."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Outdoor Sound Systems", "description": "Setting up speakers and sound systems for outdoor entertainment areas."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Countertop Installation", "description": "Placing countertops in kitchens or bathrooms."},
  {"organization_id": "Red", "category": "Electrical", "name": "Electrical Wiring", "description": "Laying electrical wiring and setting up power outlets."},
  {"organization_id": "Red", "category": "Painting", "name": "Interior Wall Painting", "description": "Painting interior walls and ceilings."},
  {"organization_id": "Red", "category": "Insulation", "name": "Installing Soundproofing", "description": "Adding soundproof materials to reduce noise between rooms."},
  {"organization_id": "Blue", "category": "HVAC", "name": "Installing Attic Fans", "description": "Setting up fans to ventilate attics and prevent heat buildup."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Toilet Setup", "description": "Installing and connecting toilets to plumbing lines."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing a Septic Tank", "description": "Installing septic systems for waste management in rural areas."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Patio Building", "description": "Building outdoor patios with wood, stone, or concrete."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing Water Softeners", "description": "Setting up systems to remove minerals from hard water."},
  {"organization_id": "Red", "category": "Tiling", "name": "Grouting Tile Joints", "description": "Filling in the spaces between tiles with grout for a finished look."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Installing Garage Shelving", "description": "Building or installing shelving units in garages for storage."},
  {"organization_id": "Blue", "category": "Structural", "name": "Steel Reinforcement Tying", "description": "Securing steel rebar together for reinforced concrete construction."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Garage Door Installation", "description": "Placing and connecting garage doors."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Shingle Removal", "description": "Removing old shingles before installing new roofing materials."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Patio Construction", "description": "Building outdoor patios from wood, stone, or concrete."},
  {"organization_id": "Red", "category": "Electrical", "name": "Solar Power Setup", "description": "Installing solar panels for energy generation."},
  {"organization_id": "Red", "category": "Electrical", "name": "Light Fixture Setup", "description": "Installing lighting fixtures and wiring."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Dismantling Scaffolding", "description": "Taking down scaffolding structures after project completion."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Sprinkler System Setup", "description": "Installing automatic irrigation systems for lawns and gardens."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Temporary Lighting Installation", "description": "Setting up lights for use during construction work."},
  {"organization_id": "Red", "category": "Concrete", "name": "Rebar Installation", "description": "Installing reinforcing steel bars (rebar) in concrete for strength."},
  {"organization_id": "Red", "category": "Roofing", "name": "Repairing Gutters", "description": "Fixing or replacing sections of gutters to ensure proper drainage."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Fence Gate Installation", "description": "Adding gates to fences for access control."},
  {"organization_id": "Blue", "category": "Waterproofing", "name": "Waterproof Membrane Installation", "description": "Applying membranes to prevent water intrusion in walls or roofs."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Fence Installation", "description": "Building fences around the property for security and privacy."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Metal Roofing Installation", "description": "Installing metal sheets for durable roofing."},
  {"organization_id": "Red", "category": "Electrical", "name": "Setting Up Temporary Lighting", "description": "Installing temporary lighting systems for use during construction."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Framing", "description": "Building the structural framework for walls, floors, and roofs."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Hardscape Installation", "description": "Building walkways, patios, and other hard surfaces in landscaping."},
  {"organization_id": "Red", "category": "Painting", "name": "Painting Exterior Trim", "description": "Applying fresh coats of paint to the exterior trim of buildings."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Balcony Construction", "description": "Building and installing balconies for outdoor access."},
  {"organization_id": "Red", "category": "Structural", "name": "Installing Steel Beams", "description": "Placing steel beams for structural support in large buildings."},
  {"organization_id": "Blue", "category": "Interior", "name": "Installing Curtain Rods", "description": "Placing curtain rods to hang window coverings."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Irrigation System Installation", "description": "Setting up systems to water gardens and lawns automatically."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Intercom System Installation", "description": "Placing intercom systems for communication between rooms."},
  {"organization_id": "Red", "category": "Exterior", "name": "Applying Stucco to Walls", "description": "Applying stucco to exterior walls for protection and aesthetics."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Operating Heavy Equipment", "description": "Using bulldozers, excavators, and other heavy machinery."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Building Raised Garden Beds", "description": "Constructing raised beds for gardening."},
  {"organization_id": "Blue", "category": "Landscaping", "name": "Paver Patio Construction", "description": "Building a patio using paver stones."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Cistern Installation", "description": "Building tanks to store rainwater for later use."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Manhole Cover Installation", "description": "Placing manhole covers for access to underground utilities."},
  {"organization_id": "Red", "category": "Structural", "name": "Erecting Structural Steel", "description": "Building the steel framework for large commercial or residential buildings."},
  {"organization_id": "Blue", "category": "Roofing", "name": "Green Roof Installation", "description": "Adding vegetation to rooftops for insulation and environmental benefits."},
  {"organization_id": "Red", "category": "Masonry", "name": "Laying Brick Driveways", "description": "Building driveways using bricks or pavers for durability."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Electrical Conduit", "description": "Running electrical conduit to protect wiring."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Foundation Laying", "description": "Pouring and leveling the foundation for the structure."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing Water Purifiers", "description": "Setting up water filtration systems to ensure clean drinking water."},
  {"organization_id": "Red", "category": "Electrical", "name": "Ceiling Fan Installation", "description": "Mounting ceiling fans for ventilation and cooling."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Water Heater Installation", "description": "Placing and connecting a water heater for the building."},
  {"organization_id": "Blue", "category": "Fire Safety", "name": "Fire Sprinkler System Installation", "description": "Setting up sprinklers for automatic fire suppression."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Constructing Outdoor Kitchens", "description": "Building outdoor kitchen areas with grills, sinks, and countertops."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Excavating Foundations", "description": "Digging out the foundation area for building construction."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Electrical Conduit Installation", "description": "Placing protective conduit for electrical wiring."},
  {"organization_id": "Red", "category": "Masonry", "name": "Building Fire Pits", "description": "Constructing outdoor fire pits using bricks or stone."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Building Carports", "description": "Constructing covered parking areas to protect vehicles."},
  {"organization_id": "Blue", "category": "Site Preparation", "name": "Site Surveying", "description": "Measuring and marking the site to ensure proper alignment of structures."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Installing Backflow Preventers", "description": "Setting up devices to prevent water contamination."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Swimming Pool Construction", "description": "Building a swimming pool from concrete and other materials."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Hot Water Heater Installation", "description": "Setting up water heaters for hot water supply."},
  {"organization_id": "Blue", "category": "Structural", "name": "Retrofitting Seismic Supports", "description": "Adding supports to make buildings more resistant to earthquakes."},
  {"organization_id": "Red", "category": "Tiling", "name": "Repairing Broken Tiles", "description": "Replacing damaged or broken tiles on floors or walls."},
  {"organization_id": "Red", "category": "Electrical", "name": "Erecting Light Poles", "description": "Installing poles to support outdoor lighting systems."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Fixing Broken Windows", "description": "Repairing or replacing broken windowpanes."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Repairing Foundation Cracks", "description": "Fixing cracks in foundations to prevent structural damage."},
  {"organization_id": "Blue", "category": "Plumbing", "name": "Manhole Cover Replacement", "description": "Swapping out old manhole covers with new ones."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Tilt-Up Construction", "description": "Constructing walls by pouring concrete into forms on-site and lifting them into place."},
  {"organization_id": "Red", "category": "Plumbing", "name": "Bathtub Placement", "description": "Installing bathtubs in bathrooms."},
  {"organization_id": "Red", "category": "Painting", "name": "Exterior Painting", "description": "Applying paint or coatings to the outer surfaces of a building."},
  {"organization_id": "Red", "category": "Landscaping", "name": "Tree Removal", "description": "Cutting down and removing trees obstructing construction work."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Security System Installation", "description": "Setting up security cameras and alarms around the building."},
  {"organization_id": "Blue", "category": "Electrical", "name": "Wind Turbine Installation", "description": "Setting up wind turbines for renewable energy generation."},
  {"organization_id": "Red", "category": "Exterior", "name": "Awning Installation", "description": "Installing awnings to provide shade over windows and doors."},
  {"organization_id": "Red", "category": "Roofing", "name": "Roofing Installation", "description": "Laying down roofing materials such as tiles, shingles, or metal sheets."},
  {"organization_id": "Blue", "category": "Waterproofing", "name": "Basement Waterproofing", "description": "Sealing the basement to prevent water leakage and damage."},
  {"organization_id": "Red", "category": "Structural", "name": "Installing Reinforcing Steel", "description": "Placing reinforcing steel bars in concrete forms for structural strength."},
  {"organization_id": "Red", "category": "Masonry", "name": "Countertop Fitting", "description": "Installing countertops in kitchens or bathrooms."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Building Chicken Coops", "description": "Constructing enclosures for raising chickens."},
  {"organization_id": "Red", "category": "Site Preparation", "name": "Building Temporary Structures", "description": "Erecting temporary structures for use during construction."},
  {"organization_id": "Blue", "category": "Exterior", "name": "Gate Installation", "description": "Placing gates at the entrance of the property for security."},
  {"organization_id": "Blue", "category": "Masonry", "name": "Concrete Block Laying", "description": "Building walls using concrete blocks."},
  {"organization_id": "Red", "category": "HVAC", "name": "Installing Radiant Floor Heating", "description": "Setting up underfloor heating systems for warmth and comfort."},
  {"organization_id": "Red", "category": "Exterior", "name": "Building Security Fences", "description": "Constructing fences for added security around properties."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Garage Door Setup", "description": "Installing or replacing garage doors."},
  {"organization_id": "Blue", "category": "Structural", "name": "Truss Installation", "description": "Setting up roof trusses for structural support."},
  {"organization_id": "Blue", "category": "Painting", "name": "Interior Painting", "description": "Coating interior walls and ceilings with paint."},
  {"organization_id": "Blue", "category": "Concrete", "name": "Concrete Repair", "description": "Fixing cracks and damage in existing concrete structures."},
  {"organization_id": "Red", "category": "Electrical", "name": "Installing Fire Alarms", "description": "Placing fire alarm systems in homes and commercial spaces."},
  {"organization_id": "Red", "category": "Carpentry", "name": "Constructing Mailbox Posts", "description": "Building or installing posts for mailboxes at the front of properties."},
  {"organization_id": "Blue", "category": "Carpentry", "name": "Building Wheelchair Ramps", "description": "Constructing ramps to provide access for wheelchair users."},
]
Task.insert_all!(tasks_attributes)

puts "#{Task.count} Tasks in archive!"
